sudo: false
language: java
os:
- linux
jdk:
- oraclejdk8
branches:
  except:
    - /.*wip.*/i
script: "mvn -T4 clean package"
after_success:
- mvn clean test jacoco:report coveralls:report -pl applier 
- "[ ${TRAVIS_PULL_REQUEST} = 'false' ] && [ ${TRAVIS_BRANCH} = 'master' ] && mvn clean deploy -DskipTests --settings ./deploy-settings.xml"
